const STATE_PLANNED = 'Planned'
const STATE_LIVE = 'Live'
const STATE_PENDING = 'Pending'
const STATE_CANCELLED = 'Cancelled'

export const STATES_AUDIO_CHATS = {
  0: STATE_PLANNED,
  1: STATE_LIVE,
  2: STATE_CANCELLED,
  3: STATE_PENDING,

  PLANNED: STATE_PLANNED,
  LIVE: STATE_LIVE,
  CANCELLED: STATE_CANCELLED,
  PENDING: STATE_PENDING,
}
