const STATE_PLANNED_LABEL = 'Planned'
const STATE_LIVE_LABEL = 'Live'
const STATE_READY_LABEL = 'Ready'
const STATE_CANCELLED_LABEL = 'Cancelled'
const STATE_FINISHED_LABEL = 'Finished'

const STATE_PLANNED_VALUE = 0
const STATE_LIVE_VALUE = 1
const STATE_READY_VALUE = 2
const STATE_CANCELLED_VALUE = 3
const STATE_FINISHED_VALUE = 4

export const DICTIONARY_STATES_AUDIO_CHATS = {
  [STATE_PLANNED_VALUE]: STATE_PLANNED_LABEL,
  [STATE_LIVE_VALUE]: STATE_LIVE_LABEL,
  [STATE_READY_VALUE]: STATE_READY_LABEL,
  [STATE_CANCELLED_VALUE]: STATE_CANCELLED_LABEL,
  [STATE_FINISHED_VALUE]: STATE_FINISHED_LABEL,

  PLANNED: {
    label: STATE_PLANNED_LABEL,
    value: STATE_PLANNED_VALUE,
  },
  LIVE: {
    label: STATE_LIVE_LABEL,
    value: STATE_LIVE_VALUE,
  },
  CANCELLED: {
    label: STATE_CANCELLED_LABEL,
    value: STATE_CANCELLED_VALUE,
  },
  READY: {
    label: STATE_READY_LABEL,
    value: STATE_READY_VALUE,
  },
  FINISHED: {
    label: STATE_FINISHED_LABEL,
    value: STATE_FINISHED_VALUE,
  },
}
